# Generated by Django 3.2.13 on 2023-01-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
