# Generated by Django 3.2.13 on 2023-01-27 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20230127_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySynonyms',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('one_way', 'One way'), ('multi_way', 'Multi way')], max_length=100)),
                ('root_word', models.CharField(blank=True, max_length=100, null=True)),
                ('words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
    ]
