# Generated by Django 3.2.13 on 2023-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_categorysynonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysynonyms',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
